server:
  port: 9001

eureka:
  instance:
    hostname: server1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server2:9002/eureka/,http://server3:9003/eureka/
  server:
    enable-self-preservation: false