eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:9001/eureka/,http://server2:9002/eureka/,http://server3:9003/eureka/
server:
  port: 9101
spring:
  application:
    name: s-user
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://sr-zipkin/
    enabled: true
  sleuth:
    sampler:
      percentage: 1