eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:9001/eureka/,http://server2:9002/eureka/,http://server3:9003/eureka/
server:
  port: 9011
spring:
  application:
    name: s-feign
  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 100Mb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  zipkin:
    base-url: http://sr-zipkin/
    enabled: true
  sleuth:
    sampler:
      percentage: 1
feign:
  hystrix:
    enabled: true