eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:9001/eureka/,http://server2:9002/eureka/,http://server3:9003/eureka/
server:
  port: 8888
spring:
  application:
    name: sr-config
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: ENC(KfDmECiR/vcDDkM1J8t6ixrv5daNpojj8qMhf6Q6n1XLKwGPgoFJG87uZyygoRRg)
          search-paths: dev
          username:
          password:
      label: master
      allow-override: true
      override-none: true
      override-system-properties: false
  rabbitmq:
    host: 139.224.195.76
    port: 5672
    username: admin
    password: admin

jasypt:
  encryptor:
    password: config
#SpringCloud 1.5版本暴露接口，暴露/bus-refresh接口
#management:
#  security:
#    enabled: false
#SpringCloud 2.0.0版本以后暴露接口方式
  endpoints:
    web:
      exposure:
        include: "*"

#是否开启基本的鉴权，默认为true
#security:
#  basic:
#    enabled: false

#忽略网卡在启动命令后面加--spring.cloud.inetutils.ignored-interfaces=eth0