eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:9001/eureka/,http://server2:9002/eureka/,http://server3:9003/eureka/
server:
  port: 9021
spring:
  application:
    name: s-file
  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 100Mb
  rabbitmq:
    host: 118.123.16.211
    port: 5672
    username: admin
    password: admin
  zipkin:
    base-url: http://sr-zipkin/
    enabled: true
  sleuth:
    sampler:
      percentage: 1