server:
  port: 9002

eureka:
  instance:
    hostname: server2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server3:9001/eureka/,http://server3:9003/eureka/