

zuul:
  addProxyHeaders: true
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000
    max-total-connections: 2000
    max-per-route-connections: 200
  routes:
    api-a:
      path: /user-api/**
      serviceId: s-feign
      stripPrefix: false
    api-b:
      path: /admin-api/**
      serviceId: s-feign
      stripPrefix: false
    api-c:
      path: /file-api/**
      serviceId: s-feign
      stripPrefix: false
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000

ribbon:
 ReadTimeout: 60000  # 单位毫秒数
 SocketTimeout: 60000


spring:
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 100Mb
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
