

zuul:
  addProxyHeaders: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    api-a:
      path: /user-api/**
      serviceId: s-feign
      stripPrefix: false
    api-b:
      path: /admin-api/**
      serviceId: s-feign
      stripPrefix: false



