eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:9001/eureka/,http://server2:9002/eureka/,http://server3:9003/eureka/
server:
  port: 9010
spring:
  application:
    name: s-zuul

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    api-a:
      path: /user-api/**
      serviceId: s-feign
    api-b:
      path: /admin-api/**
      serviceId: s-feign



