server:
  port: 9003

eureka:
  instance:
    hostname: server3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server1:9001/eureka/,http://server2:9002/eureka/