eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:9001/eureka/,http://server2:9002/eureka/,http://server3:9003/eureka/
server:
  port: 9411
spring:
  application:
    name: sr-zipkin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    #关闭本工程的推送到zipkin服务的功能
    enabled: false
