logging:
  level:
    org.springframework.cloud.gateway: debug


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #是否与服务注册于发现组件进行结合,
          #设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
          lowerCaseServiceId: true
          #开启小写验证，默认feign根据服务名查找都是用的全大写
      routes:
        - id: s-admin
          uri: lb://s-admin     #lb:从eureka中获取服务
          predicates:
            - Path=/s-admin/**

